export const apiKeys = {
    SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL as string,
    SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY as string,
    SUPABASE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY as string,
    RSA_PUBLIC_KEY_PEM: process.env.NEXT_PUBLIC_RSA_PUBLIC_KEY_PEM as string,
    RSA_PRIVATE_KEY_PEM: process.env.RSA_PRIVATE_KEY_PEM as string,
    POST_CREATE_NEW_USER: process.env.NEXT_PUBLIC_POST_CREATE_NEW_USER as string,
    POST_USER_LOGIN: process.env.NEXT_PUBLIC_POST_USER_LOGIN as string,
    POST_REFRESH_TOKEN: process.env.NEXT_PUBLIC_POST_REFRESH_TOKEN as string,
    POST_VERIFY_TOKEN: process.env.NEXT_PUBLIC_POST_VERIFY_TOKEN as string,
    POST_CREATE_WORKSPACE: process.env.NEXT_PUBLIC_POST_CREATE_WORKSPACE as string,
    POST_CREATE_TASK:process.env. NEXT_PUBLIC_POST_CREATE_TASK as string,
    POST_USER_AVATAR: process.env.NEXT_PUBLIC_POST_USER_AVATAR as string,
    GET_USER_WORKSPACE: process.env.NEXT_PUBLIC_GET_USER_WORKSPACE as string,
    GET_USER_DATA: process.env.NEXT_PUBLIC_GET_USER_DATA as string,
    GET_USER_TASKS: process.env.NEXT_PUBLIC_GET_USER_TASKS as string,
    GET_TASK: process.env.NEXT_PUBLIC_GET_TASK as string,
    DELETE_TASK: process.env.NEXT_PUBLIC_DELETE_TASK as string,
    PATCH_TASK_STATUS: process.env.NEXT_PUBLIC_PATCH_TASK_STATUS as string,
    PUT_TASK: process.env.NEXT_PUBLIC_PUT_TASK as string,
    NEXT_PUBLIC_TIME_ZONE: 'America/Toronto',
}