import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

const RootLayoutClient = ({
    children,
}: {
    children: React.ReactNode;
}) => {
    return (
        <>
            {children}
        </>
        
    )
}

export default RootLayoutClient;