import type { Metadata } from "next";
import { UserProvider } from "../context/UserContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

const RootLayoutClient = ({
    children,
}: {
    children: React.ReactNode;
}) => {
    return (
        <UserProvider>
            {children}
        </UserProvider>
    )
}

export default RootLayoutClient;