"use client"
import { Provider } from "react-redux";
import type { Metadata } from "next";
import store from "../../redux/store";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

const RootLayoutClient = ({
    children,
}: {
    children: React.ReactNode;
}) => {
    return (
        <Provider store={store}>
            {children}
        </Provider>
    )
}

export default RootLayoutClient;