import type { Metadata } from "next";
import { UserProvider } from "../../context/UserContext";
import { DateProvider } from "@/context/DateContext";
import { ThemeProvider } from "@/context/ThemeContext";
import { TaskProvider } from "@/context/TaskContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

const RootLayoutClient = ({
    children,
}: {
    children: React.ReactNode;
}) => {
    return (
        <TaskProvider>
            <DateProvider>
                <UserProvider>
                    <ThemeProvider>
                        {children}
                    </ThemeProvider>
                </UserProvider>
            </DateProvider>
        </TaskProvider>
    )
}

export default RootLayoutClient;